name: Create PTU release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Localization version'
        required: true
      gameVersion:
        description: 'Game version'
        default: '3.15.1'
        required: true
      preRelease:
        description: 'Pre-Release'
        default: 'true'
        required: true

jobs:
  build_ptu:
    runs-on: ubuntu-latest

    steps:
      - name: Chekout
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Generate Files Index
        run: python gen_files_index.py
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}-ptu
          release_name: ${{ github.event.inputs.version }} (for ${{ github.event.inputs.gameVersion }}-PTU)
          draft: false
          prerelease: ${{ github.event.inputs.preRelease }}
          
      - name: Upload Release Files Index
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./index.txt
          asset_name: index.txt
          asset_content_type: application/zip
